bag = [
    'natasha looking down',
    'steve rogers speaking',
    'scott inside home',
    'clint looking at the river',
    'natasha holding a gun',
    'tony',
    'steve rogers wearing suit',
    'barton, scott and nebulla wearing suit',
    'james and barton wearing suit',
    'natasha, nebulla, tony wearing suit',
    'thor talking to danvers',
    'danvers listening to thor',
    'thor speaking to danvers and natasha',
    'avengers hall',
    'avengers hall',
    'tony looking at the logo',
    'scott and hop',
    'tony standing infront of mountains',
    'natasha inside home',
    'tony speaking to many people',
    'peter pointing his finger',
    'james and clint wearing suit',
    'steve rogers wearing suit',
    'clint, scott and nebulla wearing suit',
    'natasha, nebulla, tony wearing suit',
    'danvers listening to thor',
    'clint turning back',
    'tony inside home',
    'clint, james, tony, steve, nebulla, scott and natasha are standing',
    'steve speaking to tony',

    'iron man helmet lying on the floor',
    'statue of liberty',
    'statue of liberty',
    'steve rogers',
    'steve rogers',
    'clint barton teaches archery to lila barton',
    'lila barton shoots arrow',
    'clint barton turns back',
    'clint barton turns back',
    'natasha holds umbrella',
    'natasha sitting on a chair',
    'steve rogers talking',
    'banner looking towards left',
    'scott looking at the pole',
    'natasha and clint are taking'
]